version: "3.5"

services:
  go:
    container_name: go-friend-local
    image: golang:1.13
    links:
      - html2pdf
    environment:
      DATABASE_URL: postgres://friend:p123123@db:5432/friend?sslmode=disable

  db:
    ports:
      - "5432:5432"
    container_name: db-friend-local
    image: postgres:9.5.20-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: friend
      POSTGRES_PASSWORD: p123123
      POSTGRES_DB: friend

  db-migrate:
    container_name: db-migrate-friend-local
    image: migrate/migrate:v3.3.0
    restart: "no"
    entrypoint: ""
    environment:
      DATABASE_URL: postgres://friend:p123123@db:5432/friend?sslmode=disable

  alpine:
    container_name: alpine-friend-local
    image: alpine
    restart: "no"

  html2pdf:
    container_name: http2pdf-friend-local
    image: arachnysdocker/athenapdf-service
    restart: "no"
