# Refer to https://github.com/volatiletech/sqlboiler#configuration
pkgname="models"
output="models"
no-tests="true"
[psql]
  dbname="friend"
  host="localhost"
  port=5432
  user="friend"
  pass="p123123"
  schema="public"
  sslmode="disable"
  blacklist=["schema_migrations"]